### ISSUE TITLE
Fetching magnets from other websites

### ISSUE THREAD

**Issue by v0dy** [fastcast/fastcast#9]
Hi! 
I'am trying to fetch and play your torrent in http://cinematrix.one/ but they only seems to be working if i open your site in another browser tab with the video iam trying to stream. How come? 

This also seem to be true when testing to download the files via https://instant.io/

regards

**Comment by jakefb** [comment]
Hi @v0dy,

Thanks for trying to test the Fastcast videos in Cinematrix!  You are trying to load the torrent from a magnet url with no peers. You need the torrent metadata to start downloading it from a [webseed](https://fastcast.nz/downloads/awakening-new-zealand-4k.mp4). 

The reason the video only loads when you open Fastcast in a new tab, is because once a web peer connects, the torrent metadata is received from that peer.

Fastcast uses a XHR to load the torrent file, which includes the metadata needed to start downloading the video from the web seeds. The solution would be to upload the torrent files to your server and make a XHR like in the code [here](https://github.com/fastcast/fastcast/blob/master/client/stream-torrent.js#L10) or make a XHR to my server. CORS is enabled for https://fastcast.nz/ so this should work.

**Comment by v0dy** [comment]
Hi @jakefb!

Thx for the help! I was able to make it work just by passing the adress to your torrent to webtorrent instead of the magnet url, this seems to be working, Is this ok by you? also i'am directly linking to  your images in order to get the movie "covers" in my API, do you want me to have these on my own server or is this ok?

**Comment by jakefb** [comment]
Nice work! Yeah this is fine, just as long as you know that the links may change when the MVC is set up so users can define their own content. Feel free to contribute any improvements you make back to Fastcast!
